package app.tmark

// Only the default registry's composition lives here. Wire schemas belong to their types.
internal fun builtInTypes(): Array<NodeType<*>> = arrayOf(
    Document,
    Caption,
    AttachedMedia,
    Link,
    AnchorLink,
    Reference,
    ReferenceLink,
    Bold,
    Italic,
    Marked,
    Underline,
    Strikethrough,
    Spoiler,
    Subscript,
    Superscript,
    DateTimeNode,
    Code,
    Math,
    Icon,
    Paragraph,
    Header,
    Preformatted,
    MathBlock,
    Anchor,
    Divider.type,
    Blockquote,
    PullQuote,
    Collage,
    Slideshow,
    ListBlock,
    ListItem,
    MapBlock,
    ImageNode,
    VideoNode,
    AudioNode,
    Table,
    TableRow,
    Cell,
    Details,
)
